name: Selenium Java Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run Tests and Save Logs
        run: |
          mvn clean test | tee test-output.log

      - name: Upload Full Maven Logs
        uses: actions/upload-artifact@v4
        with:
          name: maven-full-logs
          path: test-output.log

  notify:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Send Slack Notification
        run: |
          STATUS="${{ needs.test.result }}"
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"Selenium Java test job finished with status: *$STATUS*\"}" \
          $SLACK_WEBHOOK_URL